project:
  type: website
  output-dir: docs

website:
  title: "JinKang Personal Website"
  favicon: favicon.png
  navbar:
    logo: imgs/logo.png
    left:
      - href: index.qmd
        text: Home
      - myProjects.qmd
      - Experience.qmd
      - Reflection.qmd

format:
  html:
    theme: darkly
    css: styles.css



